kind: page
version: 1
groupId: 019f0b3c-6522-7a7e-89ea-bb3a487fa8ad
system: true
layout: admin
locales:
  - locale: en-us
    slug: /admin/pages
    title: Pages
    meta: {}
    hiddenLayoutWidgets: []
    widgets: []
  - locale: es-us
    slug: /admin/pages
    title: Páginas
    meta: {}
    hiddenLayoutWidgets: []
    widgets: []
