kind: page
version: 1
groupId: 019ef6b7-da2c-7ecb-b0d5-94002fc067c9
system: false
layout: default
locales:
  - locale: en-us
    slug: /about
    title: About
    meta: {}
    hiddenLayoutWidgets: []
    widgets:
      - zone: main
        kind: dynamic
        order: 0
        options:
          definitionId: 019ee6e4-7e2f-713d-8f83-c43163eafebc
        content:
          kicker: ""
          headline: About
      - zone: sidebar
        kind: markdown
        order: 0
        options:
          size: full
        content: ""
  - locale: es-us
    slug: /about
    title: About
    meta: {}
    hiddenLayoutWidgets: []
    widgets:
      - zone: main
        kind: dynamic
        order: 0
        options:
          definitionId: 019ee6e4-7e2f-713d-8f83-c43163eafebc
        content:
          kicker: ""
          headline: About (es-us)
      - zone: sidebar
        kind: debug
        order: 0
        options: {}
        content: {}
