/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiLayoutsIdRouteImport } from './routes/api/layouts/$id'
import { Route as ApiAuthSessionsRouteImport } from './routes/api/auth/sessions'
import { Route as AuthedAdminZonesIndexRouteImport } from './routes/_authed/admin/zones/index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users/index'
import { Route as AuthedAdminPagesIndexRouteImport } from './routes/_authed/admin/pages/index'
import { Route as AuthedAdminLayoutsIndexRouteImport } from './routes/_authed/admin/layouts/index'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users/$userId'
import { Route as AuthedAdminLayoutsLayoutIdRouteImport } from './routes/_authed/admin/layouts/$layoutId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/_authed/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutsIdRoute = ApiLayoutsIdRouteImport.update({
  id: '/api/layouts/$id',
  path: '/api/layouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionsRoute = ApiAuthSessionsRouteImport.update({
  id: '/api/auth/sessions',
  path: '/api/auth/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminZonesIndexRoute = AuthedAdminZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPagesIndexRoute = AuthedAdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminLayoutsIndexRoute = AuthedAdminLayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminLayoutsLayoutIdRoute =
  AuthedAdminLayoutsLayoutIdRouteImport.update({
    id: '/layouts/$layoutId',
    path: '/layouts/$layoutId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/layouts/': typeof AuthedAdminLayoutsIndexRoute
  '/admin/pages/': typeof AuthedAdminPagesIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/admin/zones/': typeof AuthedAdminZonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/layouts': typeof AuthedAdminLayoutsIndexRoute
  '/admin/pages': typeof AuthedAdminPagesIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/admin/zones': typeof AuthedAdminZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/_authed/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/layouts/': typeof AuthedAdminLayoutsIndexRoute
  '/_authed/admin/pages/': typeof AuthedAdminPagesIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/admin/zones/': typeof AuthedAdminZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/api/openapi.json'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/admin/'
    | '/api/users/'
    | '/admin/layouts/$layoutId'
    | '/admin/users/$userId'
    | '/admin/layouts/'
    | '/admin/pages/'
    | '/admin/users/'
    | '/admin/zones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/openapi.json'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/admin'
    | '/api/users'
    | '/admin/layouts/$layoutId'
    | '/admin/users/$userId'
    | '/admin/layouts'
    | '/admin/pages'
    | '/admin/users'
    | '/admin/zones'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_authed/admin'
    | '/api/openapi.json'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/_authed/admin/'
    | '/api/users/'
    | '/_authed/admin/layouts/$layoutId'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/layouts/'
    | '/_authed/admin/pages/'
    | '/_authed/admin/users/'
    | '/_authed/admin/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiAuthSessionsRoute: typeof ApiAuthSessionsRoute
  ApiLayoutsIdRoute: typeof ApiLayoutsIdRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layouts/$id': {
      id: '/api/layouts/$id'
      path: '/api/layouts/$id'
      fullPath: '/api/layouts/$id'
      preLoaderRoute: typeof ApiLayoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sessions': {
      id: '/api/auth/sessions'
      path: '/api/auth/sessions'
      fullPath: '/api/auth/sessions'
      preLoaderRoute: typeof ApiAuthSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/zones/': {
      id: '/_authed/admin/zones/'
      path: '/zones'
      fullPath: '/admin/zones/'
      preLoaderRoute: typeof AuthedAdminZonesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/pages/': {
      id: '/_authed/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthedAdminPagesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/layouts/': {
      id: '/_authed/admin/layouts/'
      path: '/layouts'
      fullPath: '/admin/layouts/'
      preLoaderRoute: typeof AuthedAdminLayoutsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/layouts/$layoutId': {
      id: '/_authed/admin/layouts/$layoutId'
      path: '/layouts/$layoutId'
      fullPath: '/admin/layouts/$layoutId'
      preLoaderRoute: typeof AuthedAdminLayoutsLayoutIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminLayoutsLayoutIdRoute: typeof AuthedAdminLayoutsLayoutIdRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminLayoutsIndexRoute: typeof AuthedAdminLayoutsIndexRoute
  AuthedAdminPagesIndexRoute: typeof AuthedAdminPagesIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
  AuthedAdminZonesIndexRoute: typeof AuthedAdminZonesIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminLayoutsLayoutIdRoute: AuthedAdminLayoutsLayoutIdRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminLayoutsIndexRoute: AuthedAdminLayoutsIndexRoute,
  AuthedAdminPagesIndexRoute: AuthedAdminPagesIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
  AuthedAdminZonesIndexRoute: AuthedAdminZonesIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiAuthSessionsRoute: ApiAuthSessionsRoute,
  ApiLayoutsIdRoute: ApiLayoutsIdRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
