/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiLayoutsIdRouteImport } from './routes/api/layouts/$id'
import { Route as ApiAuthSessionsRouteImport } from './routes/api/auth/sessions'
import { Route as AuthedAdminZonesIndexRouteImport } from './routes/_authed/admin/zones/index'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/admin/users/index'
import { Route as AuthedAdminPagesIndexRouteImport } from './routes/_authed/admin/pages/index'
import { Route as AuthedAdminMenusIndexRouteImport } from './routes/_authed/admin/menus/index'
import { Route as AuthedAdminLayoutsIndexRouteImport } from './routes/_authed/admin/layouts/index'
import { Route as AuthedAdminCustomWidgetsIndexRouteImport } from './routes/_authed/admin/custom-widgets/index'
import { Route as AuthedAdminConfigIndexRouteImport } from './routes/_authed/admin/config/index'
import { Route as AuthedAdminUsersUserIdRouteImport } from './routes/_authed/admin/users/$userId'
import { Route as AuthedAdminMenusMenuIdRouteImport } from './routes/_authed/admin/menus/$menuId'
import { Route as AuthedAdminLayoutsLayoutIdRouteImport } from './routes/_authed/admin/layouts/$layoutId'
import { Route as AuthedAdminCustomWidgetsWidgetIdRouteImport } from './routes/_authed/admin/custom-widgets/$widgetId'
import { Route as AuthedAdminConfigConfigIdRouteImport } from './routes/_authed/admin/config/$configId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/_authed/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLayoutsIdRoute = ApiLayoutsIdRouteImport.update({
  id: '/api/layouts/$id',
  path: '/api/layouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionsRoute = ApiAuthSessionsRouteImport.update({
  id: '/api/auth/sessions',
  path: '/api/auth/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminZonesIndexRoute = AuthedAdminZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPagesIndexRoute = AuthedAdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminMenusIndexRoute = AuthedAdminMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminLayoutsIndexRoute = AuthedAdminLayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCustomWidgetsIndexRoute =
  AuthedAdminCustomWidgetsIndexRouteImport.update({
    id: '/custom-widgets/',
    path: '/custom-widgets/',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminConfigIndexRoute = AuthedAdminConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminUsersUserIdRoute = AuthedAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminMenusMenuIdRoute = AuthedAdminMenusMenuIdRouteImport.update({
  id: '/menus/$menuId',
  path: '/menus/$menuId',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminLayoutsLayoutIdRoute =
  AuthedAdminLayoutsLayoutIdRouteImport.update({
    id: '/layouts/$layoutId',
    path: '/layouts/$layoutId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminCustomWidgetsWidgetIdRoute =
  AuthedAdminCustomWidgetsWidgetIdRouteImport.update({
    id: '/custom-widgets/$widgetId',
    path: '/custom-widgets/$widgetId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminConfigConfigIdRoute =
  AuthedAdminConfigConfigIdRouteImport.update({
    id: '/config/$configId',
    path: '/config/$configId',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/admin/config/$configId': typeof AuthedAdminConfigConfigIdRoute
  '/admin/custom-widgets/$widgetId': typeof AuthedAdminCustomWidgetsWidgetIdRoute
  '/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/admin/menus/$menuId': typeof AuthedAdminMenusMenuIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/config/': typeof AuthedAdminConfigIndexRoute
  '/admin/custom-widgets/': typeof AuthedAdminCustomWidgetsIndexRoute
  '/admin/layouts/': typeof AuthedAdminLayoutsIndexRoute
  '/admin/menus/': typeof AuthedAdminMenusIndexRoute
  '/admin/pages/': typeof AuthedAdminPagesIndexRoute
  '/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/admin/zones/': typeof AuthedAdminZonesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/admin/config/$configId': typeof AuthedAdminConfigConfigIdRoute
  '/admin/custom-widgets/$widgetId': typeof AuthedAdminCustomWidgetsWidgetIdRoute
  '/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/admin/menus/$menuId': typeof AuthedAdminMenusMenuIdRoute
  '/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/admin/config': typeof AuthedAdminConfigIndexRoute
  '/admin/custom-widgets': typeof AuthedAdminCustomWidgetsIndexRoute
  '/admin/layouts': typeof AuthedAdminLayoutsIndexRoute
  '/admin/menus': typeof AuthedAdminMenusIndexRoute
  '/admin/pages': typeof AuthedAdminPagesIndexRoute
  '/admin/users': typeof AuthedAdminUsersIndexRoute
  '/admin/zones': typeof AuthedAdminZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRoute
  '/api/layouts/$id': typeof ApiLayoutsIdRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/_authed/admin/config/$configId': typeof AuthedAdminConfigConfigIdRoute
  '/_authed/admin/custom-widgets/$widgetId': typeof AuthedAdminCustomWidgetsWidgetIdRoute
  '/_authed/admin/layouts/$layoutId': typeof AuthedAdminLayoutsLayoutIdRoute
  '/_authed/admin/menus/$menuId': typeof AuthedAdminMenusMenuIdRoute
  '/_authed/admin/users/$userId': typeof AuthedAdminUsersUserIdRoute
  '/_authed/admin/config/': typeof AuthedAdminConfigIndexRoute
  '/_authed/admin/custom-widgets/': typeof AuthedAdminCustomWidgetsIndexRoute
  '/_authed/admin/layouts/': typeof AuthedAdminLayoutsIndexRoute
  '/_authed/admin/menus/': typeof AuthedAdminMenusIndexRoute
  '/_authed/admin/pages/': typeof AuthedAdminPagesIndexRoute
  '/_authed/admin/users/': typeof AuthedAdminUsersIndexRoute
  '/_authed/admin/zones/': typeof AuthedAdminZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/login'
    | '/admin'
    | '/api/openapi.json'
    | '/{-$locale}/$'
    | '/{-$locale}/'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/admin/'
    | '/api/users/'
    | '/admin/config/$configId'
    | '/admin/custom-widgets/$widgetId'
    | '/admin/layouts/$layoutId'
    | '/admin/menus/$menuId'
    | '/admin/users/$userId'
    | '/admin/config/'
    | '/admin/custom-widgets/'
    | '/admin/layouts/'
    | '/admin/menus/'
    | '/admin/pages/'
    | '/admin/users/'
    | '/admin/zones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/openapi.json'
    | '/{-$locale}/$'
    | '/{-$locale}'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/admin'
    | '/api/users'
    | '/admin/config/$configId'
    | '/admin/custom-widgets/$widgetId'
    | '/admin/layouts/$layoutId'
    | '/admin/menus/$menuId'
    | '/admin/users/$userId'
    | '/admin/config'
    | '/admin/custom-widgets'
    | '/admin/layouts'
    | '/admin/menus'
    | '/admin/pages'
    | '/admin/users'
    | '/admin/zones'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/login'
    | '/_authed/admin'
    | '/api/openapi.json'
    | '/{-$locale}/$'
    | '/{-$locale}/'
    | '/api/auth/sessions'
    | '/api/layouts/$id'
    | '/api/users/$id'
    | '/_authed/admin/'
    | '/api/users/'
    | '/_authed/admin/config/$configId'
    | '/_authed/admin/custom-widgets/$widgetId'
    | '/_authed/admin/layouts/$layoutId'
    | '/_authed/admin/menus/$menuId'
    | '/_authed/admin/users/$userId'
    | '/_authed/admin/config/'
    | '/_authed/admin/custom-widgets/'
    | '/_authed/admin/layouts/'
    | '/_authed/admin/menus/'
    | '/_authed/admin/pages/'
    | '/_authed/admin/users/'
    | '/_authed/admin/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiAuthSessionsRoute: typeof ApiAuthSessionsRoute
  ApiLayoutsIdRoute: typeof ApiLayoutsIdRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/layouts/$id': {
      id: '/api/layouts/$id'
      path: '/api/layouts/$id'
      fullPath: '/api/layouts/$id'
      preLoaderRoute: typeof ApiLayoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sessions': {
      id: '/api/auth/sessions'
      path: '/api/auth/sessions'
      fullPath: '/api/auth/sessions'
      preLoaderRoute: typeof ApiAuthSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/zones/': {
      id: '/_authed/admin/zones/'
      path: '/zones'
      fullPath: '/admin/zones/'
      preLoaderRoute: typeof AuthedAdminZonesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/users/': {
      id: '/_authed/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/pages/': {
      id: '/_authed/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthedAdminPagesIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/menus/': {
      id: '/_authed/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus/'
      preLoaderRoute: typeof AuthedAdminMenusIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/layouts/': {
      id: '/_authed/admin/layouts/'
      path: '/layouts'
      fullPath: '/admin/layouts/'
      preLoaderRoute: typeof AuthedAdminLayoutsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/custom-widgets/': {
      id: '/_authed/admin/custom-widgets/'
      path: '/custom-widgets'
      fullPath: '/admin/custom-widgets/'
      preLoaderRoute: typeof AuthedAdminCustomWidgetsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/config/': {
      id: '/_authed/admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AuthedAdminConfigIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/users/$userId': {
      id: '/_authed/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/menus/$menuId': {
      id: '/_authed/admin/menus/$menuId'
      path: '/menus/$menuId'
      fullPath: '/admin/menus/$menuId'
      preLoaderRoute: typeof AuthedAdminMenusMenuIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/layouts/$layoutId': {
      id: '/_authed/admin/layouts/$layoutId'
      path: '/layouts/$layoutId'
      fullPath: '/admin/layouts/$layoutId'
      preLoaderRoute: typeof AuthedAdminLayoutsLayoutIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/custom-widgets/$widgetId': {
      id: '/_authed/admin/custom-widgets/$widgetId'
      path: '/custom-widgets/$widgetId'
      fullPath: '/admin/custom-widgets/$widgetId'
      preLoaderRoute: typeof AuthedAdminCustomWidgetsWidgetIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/config/$configId': {
      id: '/_authed/admin/config/$configId'
      path: '/config/$configId'
      fullPath: '/admin/config/$configId'
      preLoaderRoute: typeof AuthedAdminConfigConfigIdRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminConfigConfigIdRoute: typeof AuthedAdminConfigConfigIdRoute
  AuthedAdminCustomWidgetsWidgetIdRoute: typeof AuthedAdminCustomWidgetsWidgetIdRoute
  AuthedAdminLayoutsLayoutIdRoute: typeof AuthedAdminLayoutsLayoutIdRoute
  AuthedAdminMenusMenuIdRoute: typeof AuthedAdminMenusMenuIdRoute
  AuthedAdminUsersUserIdRoute: typeof AuthedAdminUsersUserIdRoute
  AuthedAdminConfigIndexRoute: typeof AuthedAdminConfigIndexRoute
  AuthedAdminCustomWidgetsIndexRoute: typeof AuthedAdminCustomWidgetsIndexRoute
  AuthedAdminLayoutsIndexRoute: typeof AuthedAdminLayoutsIndexRoute
  AuthedAdminMenusIndexRoute: typeof AuthedAdminMenusIndexRoute
  AuthedAdminPagesIndexRoute: typeof AuthedAdminPagesIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
  AuthedAdminZonesIndexRoute: typeof AuthedAdminZonesIndexRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminConfigConfigIdRoute: AuthedAdminConfigConfigIdRoute,
  AuthedAdminCustomWidgetsWidgetIdRoute: AuthedAdminCustomWidgetsWidgetIdRoute,
  AuthedAdminLayoutsLayoutIdRoute: AuthedAdminLayoutsLayoutIdRoute,
  AuthedAdminMenusMenuIdRoute: AuthedAdminMenusMenuIdRoute,
  AuthedAdminUsersUserIdRoute: AuthedAdminUsersUserIdRoute,
  AuthedAdminConfigIndexRoute: AuthedAdminConfigIndexRoute,
  AuthedAdminCustomWidgetsIndexRoute: AuthedAdminCustomWidgetsIndexRoute,
  AuthedAdminLayoutsIndexRoute: AuthedAdminLayoutsIndexRoute,
  AuthedAdminMenusIndexRoute: AuthedAdminMenusIndexRoute,
  AuthedAdminPagesIndexRoute: AuthedAdminPagesIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
  AuthedAdminZonesIndexRoute: AuthedAdminZonesIndexRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiAuthSessionsRoute: ApiAuthSessionsRoute,
  ApiLayoutsIdRoute: ApiLayoutsIdRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
